#!/bin/bash
# FORGE Pre-Compact Hook
# Saves critical context before session compaction

set -e

# Source workspace root helper
source "$(dirname "$0")/../_lib/workspace-root.sh"

# Get workspace root (not plugin root)
WORKSPACE_ROOT="$(get_workspace_root)"
FORGE_DIR="${WORKSPACE_ROOT}/.claude/forge"
MEMORY_DIR="${FORGE_DIR}/memory"
DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "🔧 FORGE: Running pre-compact hook..."

# Create memory directory if it doesn't exist
mkdir -p "${MEMORY_DIR}/session-snapshots"
mkdir -p "${MEMORY_DIR}/.insights_pending"
mkdir -p "${FORGE_DIR}/snapshots"

# Save session context for next session
cat > "${MEMORY_DIR}/last_session_context.md" << EOF
---
session_end: ${DATE}
context_remaining: triggered
---

# Last Session Summary

Session ended at ${DATE}.

## Context Preservation

Critical information has been saved to:
- Memory graph: ${MEMORY_DIR}/graph/memory.json
- Entities: ${MEMORY_DIR}/entities/
- Patterns: ${MEMORY_DIR}/patterns/
- Learnings: ${MEMORY_DIR}/learnings/
- Session snapshots: ${FORGE_DIR}/snapshots/

## Next Session Actions

1. Run \`/forge:learn\` to process any pending insights
2. Run \`/forge:status\` to see project state
3. Use \`@skill-router\` to auto-route new tasks

---
*Auto-generated by FORGE Pre-Compact Hook*
EOF

# Create insights pending marker
if [ ! -f "${MEMORY_DIR}/.insights_pending/active" ]; then
  mkdir -p "${MEMORY_DIR}/.insights_pending"
  echo "${DATE}" > "${MEMORY_DIR}/.insights_pending/active"
  echo "📊 Insights marker created for next session"
fi

# Also create a snapshot of the current workflow state if it exists
if [ -f "${FORGE_DIR}/active-workflow.md" ]; then
  cp "${FORGE_DIR}/active-workflow.md" "${FORGE_DIR}/snapshots/workflow-${DATE}.md" 2>/dev/null || true
fi

echo "✅ Pre-compact hook complete"

exit 0
